version: '3.9'
services:
    api:
        build: './.docker/php'
        container_name: '${API_CONTAINER_NAME}'
        ports:
            - '${API_PORT:-8000}:${API_PORT:-8000}'
        volumes:
            - './backend:/var/www/html'
            - './.env:/var/www/html/.env'
            - './.docker/php/php.ini:/usr/local/etc/php/php.ini'
        depends_on:
            - db
        working_dir: '/var/www/html'
        command: 'bash -c "composer install && php artisan serve --host=${API_HOST:-0.0.0.0} --port=${API_PORT:-8000}"'
        profiles:
            - backend

    db:
        image: 'mysql'
        container_name: '${APP_ID}-db'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        profiles:
            - backend

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        ports:
            - '${PHPMYADMIN_PORT:-4000}:80'
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - db
        profiles:
            - backend

    web:
        image: 'node'
        container_name: '${WEB_CONTAINER_NAME}'
        ports:
            - '${WEB_PORT:-3000}:${WEB_PORT:-3000}'
        environment:
            HOST: '${WEB_HOST:-0.0.0.0}'
            PORT: '${WEB_PORT:-3000}'
        volumes:
            - './.env:/var/www/html/.env'
            - './frontend:/var/www/html'
        working_dir: '/var/www/html'
        command: 'bash -c "yarn && yarn dev"'
        profiles:
            - frontend
