GET /sanctum/csrf-cookie HTTP/1.1
Host: localhost:8000

###

POST /api/login HTTP/1.1
Host: localhost:8000
Content-Type: application/json
X-XSRF-TOKEN: eyJpdiI6ImY3OWtYSGFHRjlhUERFSlp0SW5sQUE9PSIsInZhbHVlIjoiRks0ZC9zVmsrTGQxVU1weUJFVEw3TlVyTEh1eHhya0IzK1VVU3cwRUZJNURyYWlGM2orajVGTDdCYkE1SUpmYVd6MmtuRktoV01SSjIwTkUzTzJxNnEyUm5jWkFucUlTQVA4c1RvOWtOeEUycW1XNC9LYUt0MjdEeFJuQU96UHAiLCJtYWMiOiI0ZWM2YzY5ODM2MDY2ZjMxYTYwMjNhMjQ4N2E4ZTA1ZWUzYTRjYmYzMDBlM2Q1ZjE0ODJhY2U4YjhkOTM4MTE2IiwidGFnIjoiIn0%3D

{
    "email": "giovanni.powlowski@example.org",
    "password": "password"
}

###

GET /api/user HTTP/1.1
Host: localhost:8000
X-XSRF-TOKEN: eyJpdiI6ImY3OWtYSGFHRjlhUERFSlp0SW5sQUE9PSIsInZhbHVlIjoiRks0ZC9zVmsrTGQxVU1weUJFVEw3TlVyTEh1eHhya0IzK1VVU3cwRUZJNURyYWlGM2orajVGTDdCYkE1SUpmYVd6MmtuRktoV01SSjIwTkUzTzJxNnEyUm5jWkFucUlTQVA4c1RvOWtOeEUycW1XNC9LYUt0MjdEeFJuQU96UHAiLCJtYWMiOiI0ZWM2YzY5ODM2MDY2ZjMxYTYwMjNhMjQ4N2E4ZTA1ZWUzYTRjYmYzMDBlM2Q1ZjE0ODJhY2U4YjhkOTM4MTE2IiwidGFnIjoiIn0%3D

###

GET /api/logout HTTP/1.1
Host: localhost:8000
X-XSRF-TOKEN: eyJpdiI6ImY3OWtYSGFHRjlhUERFSlp0SW5sQUE9PSIsInZhbHVlIjoiRks0ZC9zVmsrTGQxVU1weUJFVEw3TlVyTEh1eHhya0IzK1VVU3cwRUZJNURyYWlGM2orajVGTDdCYkE1SUpmYVd6MmtuRktoV01SSjIwTkUzTzJxNnEyUm5jWkFucUlTQVA4c1RvOWtOeEUycW1XNC9LYUt0MjdEeFJuQU96UHAiLCJtYWMiOiI0ZWM2YzY5ODM2MDY2ZjMxYTYwMjNhMjQ4N2E4ZTA1ZWUzYTRjYmYzMDBlM2Q1ZjE0ODJhY2U4YjhkOTM4MTE2IiwidGFnIjoiIn0%3D
